# fly.toml app configuration file generated for axiso-green-energy project.
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "axiso-green-energy"
primary_region = "iad"

[build]
  builder = "heroku"
  buildpacks = ["heroku/nodejs"]

[env]
  REACT_APP_SUPABASE_URL = "https://oqqzrppoqgnrinavvolz.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcXpycHBvcWducmluYXZ2b2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTM2ODUsImV4cCI6MjA1ODgyOTY4NX0.O-hdv4Op8-eg6hzBmIaUSKjl0XQdIgH2lilRPahJPrA"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 850
